blueprints/members/forms.py
from datetime import datetime
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, IntegerField, SelectField, FileField
from wtforms.validators import DataRequired, Email
from flask_wtf.file import (
    FileField, FileAllowed
)

class CSVReaderForm(FlaskForm):
    csv_file = FileField(
        'Inv CSV Feed',
        validators=[
        FileAllowed(['csv'])
        ]
        )
    submit = SubmitField('Feed Inv | Read CSV')


class MemberForm(FlaskForm):
    pass
    user_id = IntegerField('UserID')
    
    first_name = StringField('first name', validators=[
                            DataRequired()], default='Attila')
     
    middle_name = StringField('middle name', default='')
    
    last_name = StringField('last name', validators=[
                           DataRequired()], default='Turkoz')
    phone_num = StringField('phone_number', default='')
    email = StringField('email',
                        validators=[ Email()])
    gender  = SelectField(choices=[('m', 'Male'), ('f', 'Female')], default ='m')
    is_admin  = SelectField(choices=[('n', 'NO'), ('y', 'YES')], default ='n')
    is_prez  = SelectField(choices=[('n', 'NO'), ('y', 'YES')], default ='n')
    linkedin = StringField('linkedin', default='')
    instagram = StringField('instagram', default='')
    twitter = StringField('twitter', default='')
    submit = SubmitField('Add New Member!', )
    # picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'png'])])

class MemberEditForm(FlaskForm):
    pass
    user_id  = SelectField('UserID', choices=[('0', '0'), ('1', '1')], )
    first_name = StringField('first name', validators=[
                            DataRequired()])
     
    middle_name = StringField('middle name')
    
    last_name = StringField('last name', validators=[
                           DataRequired()],)
    phone_num = StringField('phone_number')
    email = StringField('email')
    gender  = SelectField('gender',choices=[('m', 'Male'), ('f', 'Female')], )
    is_admin  = SelectField('admin', choices=[('n', 'NO'), ('y', 'YES')], )
    is_prez  = SelectField('prez',choices=[('n', 'NO'), ('y', 'YES')], )
    img_url = StringField('image link', )
    linkedin = StringField('linkedin', )
    instagram = StringField('instagram', )
    twitter = StringField('twitter', )
    submit = SubmitField('save changes', )
    # picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'png'])])

class MemberMenu(FlaskForm):
    pass
    menu  = SelectField('Members', choices=[('0', '0'), ('1', '1')], )
    # submit  = SubmitField('Show')
    # emails  = SelectField('Emails', choices=[('0', '0'), ('1', '1')], )
    

blueprints/members/routes.py
import random
import os
import csv
import codecs
import requests
from flask import (
    render_template, url_for, flash,
    redirect, request, abort, Blueprint,
    jsonify
)
from flask_login import (
    login_user, current_user, logout_user, login_required)
from blueprints import db
from blueprints.models import Member, User
from blueprints.members.forms import (
    MemberForm,
    MemberMenu,
    CSVReaderForm,
    MemberEditForm
)
members = Blueprint('members', __name__)


@members.context_processor
def inject_random_theme():
  pass
  def random_theme():
    pass
    list_of_themes = [
      'cerulean',
      'cyborg',
      'darkly',
      'lumen',
      'minty',
      'pulse',
      'slate',
      'solar',
      'spacelab',
      'superhero',
      'united',
    ]
    
    selected  = random.choice(list_of_themes)
    print(selected)
    return selected if selected else 'minty'

  return dict(random_theme=random_theme())


@members.context_processor
def inject_css_class():
    pass
    def bg_row(gender):
        pass
        gallery = {  # font awesome icons for member forms
            "f": "bg-secondary border-bottom",
            "m": "bg-primary border-bottom",
        }

        return gallery.get(gender, 'bg-light')

    return dict(bg_row=bg_row)

@members.context_processor
def inject_icons():
    pass

    def icons(label):
        pass
        gallery = {  # font awesome icons for member forms
            "email": "s fa-envelope",
            "first_name": "s fa-user-edit",
            "gender": "s fa-venus-mars",
            "id": "s fa-id-card",
            "img_url": "s fa-image",
            "instagram": "b fa-instagram",
            "is_admin": "s fa-user-md",
            "is_prez": "s fa-user-md",
            "last_name": "s fa-user-edit",
            "linkedin": "b fa-linkedin",
            "middle_name": "s fa-question-circle",
            "phone_num": "s fa-phone",
            "twitter": "b fa-twitter",
            "user_id": "s fa-user-tag",
            "menu": "s fa-sort",
        }

        return gallery.get(label, 's fa-edit')

    return dict(icons=icons)

@members.route("/members/api")
def api_all():
    pass
    q_all = Member.query.all()

    members = [m for m in q_all]
    d = [
        {
            c.name: getattr(member, c.name)
            for c in member.__table__.columns
        }
        for member in members
    ]

    return jsonify(dict(enumerate(d)))


@members.route("/members/db/init")
def db_init():
    pass  # UPLOAD ZILLOW HOUSE VALUE INDEX CSV'S MERGED
    existing_data = Member.query.first()

    if existing_data:
        pass
        return jsonify({
            'status0': 'database exists',
            'status1': 'db init is one time only',
            'status2': 'no upload necessary',
        })
    else:
        pass
        csv_url = 'https://gist.githubusercontent.com/attila5287/54a88147cbdfa6de88d5de0439250f3e/raw/55cadaafc200913578deddd4b43db5badc1dc0ce/members_ext.csv'

        with requests.get(csv_url, stream=True) as r:
            pass
            lines = (line.decode('utf-8') for line in r.iter_lines())
            csv_dict = [row for row in csv.DictReader(lines)]
            members = [
                Member(**row,
                       user_id=0,
                       ) for row in csv_dict
            ]
            # print(inventory).
            db.session.add_all(members)
            db.session.commit()

        return jsonify(csv_dict)

@members.route("/members", methods=['GET', 'POST'])
@members.route("/members/", methods=['GET', 'POST'])
@members.route("/members/<string:theme>", methods=['GET', 'POST'])
def home(theme=''):
    pass
    page = request.args.get('page', 1, type=int)

    members = Member.query.order_by(
        Member.id.asc()).paginate(page=page, per_page=24)
    form = MemberMenu()
    all_members = [m for m in Member.query.all()]
    form.menu.choices = [
        (m.id, '{}, {} | {}'.format(m.last_name.upper(), str(m.first_name + ' ' + m.middle_name).title(), m.email).strip()) for m in all_members
    ]
    if request.method == 'POST':
        pass
        rf = request.form
        return redirect(url_for('members.show', id=rf['menu']))

    access = [
        'a',
        'm',
    ]

    return render_template('members.html',
                           theme=theme,
                           members=members,
                           form=form,
                           info_notes=[
                               'All members in grid view for other members to browse through. Click/tap on name to see in details or try dropdown menu.',
                           ],
                           access=[
                               'm',
                               'a',
                               'p',
                           ],
                           js=None,
                           legend='Members Grid',
                           title='Members',

                           )

@members.route('/member', methods=['GET', 'POST'])
@members.route('/member/', methods=['GET', 'POST'])
@members.route('/member/<int:id>', methods=['GET', 'POST'])
@members.route('/member/<int:id>/', methods=['GET', 'POST'])
def show(id=1, theme='no_change'):
    pass
    form = MemberMenu()
    member = Member.query.get_or_404(id)

    members = [m for m in Member.query.all()]
    form.menu.choices = [
        (m.id, '{}, {} | {}'.format(m.last_name.upper(), str(m.first_name + ' ' + m.middle_name).title(), m.email).strip()) for m in members
    ]

    if request.method == 'POST':
        pass
        rf = request.form
        return redirect(url_for('members.show', id=rf['menu']))

    elif request.method == 'GET':
        pass

    return render_template('member.html',
                           theme=theme,
                           form=form,
                           m=member,
                           info_notes=[
                               'Members gallery, choose arrow buttons or dropdown menu. Members could see other members while only admins are authorized to edit member info or assign tasks.'
                           ],
                           access=[
                               'm',
                               'a',
                               'p',
                           ],
                           js=None,
                           legend='View Member ID#{}'.format(id),
                           title='Member#{}'.format(id),
                           )

@members.route('/member/edit', methods=['GET', 'POST'])
@members.route('/member/edit/', methods=['GET', 'POST'])
@members.route('/member/edit/<int:id>', methods=['GET', 'POST'])
def edit(id=1, theme='no_change'):
    pass

    users = [u for u in User.query.all()]
    q_all = [Member.query.get_or_404(id)]
    members = [m for m in q_all]
    member = [m for m in q_all][0]
    d = [
        {
            c.name: getattr(member, c.name)
            for c in member.__table__.columns
        }
        for member in members
    ]
    form = MemberEditForm()

    if form.validate_on_submit():
        cast_into_dict = {field.name: field.data for field in form}
        cast_into_dict.pop('csrf_token', None)
        d = cast_into_dict.copy()
        for name, value in d.items():
            pass
            setattr(member, name, value)
        db.session.commit()
        return redirect(url_for('members.show', id=member.id))
        # return jsonify(d)

    elif request.method == 'GET':
        form = MemberEditForm(**dict(enumerate(d))[0])
        form.user_id.choices = [
            (u.id, '{}|{}'.format(u.email, u.username)) for u in users
        ]

    return render_template('member_edit.html',
                           theme=theme,
                           form=form,
                           info_notes=[
                               'Edit member details',
                           ],
                           access=[
                               'a',
                               'p',
                           ],
                           js=None,
                           title="EditM#{}".format(id),
                           legend="Edit Member #{}".format(id),
                           member=member,                           

                           )


@members.route("/members/table")
@members.route("/members/table/")
@members.route("/members/table/<string:theme>")
@members.route("/members/table/<string:theme>/")
def table(theme=''):
    pass
    page = request.args.get('page', 1, type=int)

    members = Member.query.order_by(
        Member.id.desc()).paginate(page=page, per_page=24)

    columns = [c.name for c in Member.query.first().__table__.columns]
    
    required_cols = [
        "img_url", 
        "id", 
        "first_name", 
        "middle_name", 
        "last_name",
        "linkedin",
        "twitter", 
        "instagram",
        "gender",
    ]
    headers = [
        "img_url", 
        "id", 
        "first_name", 
        "middle_name", 
        "last_name",
        "linkedin",
        "twitter", 
        "instagram",
        "gender",
    ]
    table = [
        {
            c:
            getattr(member, c)
            for c in required_cols}

        for member in members.items
    ]

    try:
        _ = [member for member in members.items]
    except:
        members = []

    return render_template('members_table.html', 
                           theme=theme,
                           members=members, headers=headers, table=table,
                           info_notes=[
                               'Members, Table View. ',
                           ],
                           access=[
                               'a',
                               'p',
                           ],
                           js=None,
                           legend='Members Table',
                           title='Table',
                           )

blueprints/posts/routes.py
import random
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from blueprints import db
from blueprints.models import Post, User
from blueprints.posts.forms import PostForm

posts = Blueprint('posts', __name__)
 
@posts.context_processor
def inject_random_theme():
  pass
  def random_theme():
    pass
    list_of_themes = [
      'cerulean',
      'cyborg',
      'darkly',
      'lumen',
      'minty',
      'pulse',
      'slate',
      'solar',
      'spacelab',
      'superhero',
      'united',
    ]
    _rc = random.choice
    selected  = _rc(list_of_themes)
    # print('\t\n  theme switched to {}\n'.format(selected))
    return selected if selected else 'minty'

  return dict(random_theme=random_theme())

@posts.context_processor
def inject_icons():
    pass
    def icons(label):
        pass
        gallery = { #font awesome icons
            "title": "s fa-highlighter", 
            "email": "s fa-envelope", 
            "id": "s fa-id-card", 
            "img_url": "s fa-image", 
            "is_authenticated": "s fa-plug", 
            "is_member": "s fa-user-check", 
            "is_admin": "s fa-user-md", 
            "is_prez": "s fa-user-graduate", 
            "content": "s fa-envelope-open", 
            }
        
        return gallery.get(label, 's fa-edit')
    
    return dict(icons=icons)

@posts.route("/post/new", methods=['GET', 'POST'])
@posts.route("/post/new/", methods=['GET', 'POST'])
@posts.route("/post/new/<string:theme>", methods=['GET', 'POST'])
@posts.route("/post/new/<string:theme>/", methods=['GET', 'POST'])
def new_post(theme=''):
    pass 
    user = current_user if current_user.is_authenticated else User.query.get_or_404(1)
    
    form = PostForm()
    
    if form.validate_on_submit():
        pass
        post = Post(title=form.title.data, content=form.content.data, author=user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    
    return render_template('create_post.html',
                           theme=theme,
                           user=user,
                           form=form,
                           info_notes=[
                               'Public message board, user-created messages need to be approved by an admin.',
                           ],
                           access=[
                               'u',
                               'm',
                               'a',
                               'p',
                           ],
                           js=None,
                           legend='New Post Form',
                           title='New Post',

                           )

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@posts.route("/post/<int:post_id>/update/", methods=['GET', 'POST'])
@posts.route("/post/<int:post_id>/update/<string:theme>", methods=['GET', 'POST'])
@posts.route("/post/<int:post_id>/update/<string:theme>/", methods=['GET', 'POST'])
@login_required
def update_post(post_id,theme='no_change'):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', 
                           theme=theme,
                           title='Update Post',
                           form=form, 
                           legend='Update Post'
                           )


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

@posts.route("/post/<int:post_id>")
@posts.route("/post/<int:post_id>/")
def post(post_id=1, theme='no_change'):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', 
                           theme=theme, 
                           post=post, 
                           info_notes=[
                               'Shows the selected post individually. ',
                               'Update if posted by the current user.',
                           ],
                           access=[
                               'u',
                               'm',
                               'a',
                               'p',
                           ],
                           js=None,
                           legend='View Post',
                           title=post.title, 

                           )

blueprints/templates/_btn.html
{% set filter_buttons = [
  ('primary', 'member', ), 
  ('info', 'admin', ), 
  ('danger', 'prez', ), 
  ]  %}  

  {{cat}}
  <div class="row text-center no-gutters">

    {% for style, cat in filter_buttons %}
    <div class="col-4 px-1">
      <button class="btn btn-outline-{{style}} shadow-sm mt-2 btn-block" type="button">
        <i class="fa{{icons(cat)}}">
        </i>
        {{cat}}
      </button>
    </div>
    
    {% endfor %}
      
  </div>

blueprints/templates/member_edit.html
{% extends "layout.html" %}
{% block content %}
{% set demo_mode = 'off' %}

{% if current_user.is_admin == 'y' or (current_user.is_member =='y' and current_user.id == member.user_id)  or demo_mode == 'on'%}

    <div class="container" name="memb-edit-forms">
        {% if form.errors %}
        <div class="container errors">
        {% for field_name, field_errors in form.errors|dictsort if field_errors %}
            {% for error in field_errors %}
            <div class="px-5 mx-5 alert alert-secondary border-0 alert-dismissible fade show rnd-3xl" role="alert">
                    <strong>

                        <p class="text-lg my-1">
                        <i class="text-xl fa{{ icons(form[field_name].id) }} fa-fw animated infinite heartBeat mr-2"></i>
                        {{ form[field_name].label }}: {{ error }}</p>
                    </strong>
                {{msg}}
                <button type="button" class="close text-2xl text-light" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>        
            {% endfor %}
            {% endfor %}
        </div>
        {% endif %}
        <div class="row">
            <div class="col-2 col-sm-4 col-lg-2 offset-lg-2" >
                <img class="border-0  bg-secondary add-anime member-img p-1 shadow mb-2 rnd-3xl" src="{{ member.img_url  }}"
                    alt="{{ member.id }}-photo" style="width: 95%;">
                    
            </div>
        
            <div class="col-10 col-sm-8 col-lg-6" name="form-part">
                <div class="content-section pl-4 pt-3 pr-0">
                    <fieldset class="form-group">
                        <form method="POST" action="">
                            {{ form.hidden_tag() }}
                    
                            {% for field in form %}
                            {% if field.id == 'csrf_token' %}
                            <i class="text-hide">CSRF TOKEN</i>
                            {% elif field.type == 'SubmitField' %}
                            {{field(class="btn btn-block btn-primary text-light text-xl py-2 border-0 rnd-xl shadow-lg" )}}                    
                            {% elif field.type == 'SelectField' %}
                            <div class="form-row align-items-center mb-4">
                    
                                <div class="col-2">
                                    <p class="text-monts  text-right my-0">
                                        {{field.label}}
                                    </p>
                                </div>
                                <div class="col">
                                    <div class="input-group mx-2 mb-0 ">
                                        <div class="input-group-prepend add-anime rnd-xl">
                                            <span class="input-group-text rnd-xl text-bold bg-secondary"
                                                id="inputGroupPrepend">
                                                <i class="text-light fa{{icons(field.id)}} fa-fw ml-2 mt-0"></i>
                                            </span>
                                        </div>
                                        {{field(class="custom-select custom-select-sm shadow mr-2" )}}
                                    </div>
                                </div>
                            </div>
                            {% else %}
                            <div class="form-row align-items-center mb-4">
                    
                                <div class="col-2">
                                    <p class="text-monts  text-right my-0">
                                        {{field.label}}
                                    </p>
                                </div>
                                <div class="col">
                                    <div class="input-group mx-2 mb-0 ">
                                        <div class="input-group-prepend  add-anime rnd-xl">
                                            <span class="input-group-text bg-secondary text-light rnd-xl text-bold"
                                                id="inputGroupPrepend">
                                                <i class="fa{{icons(field.id)}} fa-fw ml-2 mt-0"></i>
                                            </span>
                                        </div>
                                        {{field(class="form-control form-control-sm mb-0 shadow mr-2" )}}
                                    </div>
                                </div>
                            </div>
                    
                            {% endif %}
                    
                            {% endfor %}
                        </form>           
                    </fieldset>
                    <div class="btn-group d-flex flex-row" role="group" aria-label="Button group">
                        <a class="btn btn-secondary shadow text-lg" type="button" href="{{url_for('members.show', id=member.id )}}">
                            <i class="fas fa-times"></i>
                            Discard&Leave
                        </a>
                        <a class="btn btn-info shadow text-lg" type="button" href="{{url_for('members.edit', id=member.id )}}">
                            <i class="fas fa-undo"></i>
                            Reset&Edit
                        </a>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    {% else %}
    <div class="container" name="security-chk"> 
        <div class="col-8 offset-2 alert alert-success text-center border-0 alert-dismissible fade show rnd-3xl" role="alert">
            <p class="text-md my-1">
                 not authorized
            </p>
            <button type="button" class="close text-2xl text-light" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
    <div class="row no-gutters">
        <div class="col-2 col-sm-4 col-lg-2 offset-lg-2" >
            <img class="border-0 bg-transparent add-anime member-img p-0 m-0 shadow mb-2 rounded-circle opac-50" src="https://raw.githubusercontent.com/attila5287/rota-img/main/profile_pics/attila.png"
                alt="dev-notes" style="width: 95%;">
                
                {% set notes = [ 
                    'This is an exact replica of the requested form. ',
                    'Members could edit themselves',
                    'Admins could also edit members',
                    ] %}
                    {% for note in notes %}
                    <p class="text-bold text-italic text-info">
                        <i class="fas fa-info-circle"></i> 
                        {{note}}
                    </p>
                    
                    {% endfor %}
                
        </div>
    
        <div class="col-10 col-sm-8 col-lg-6" name="form-part">
            <div class="content-section pl-4 pt-3 pr-0">
                <fieldset class="form-group">
                    <form method="POST" action="">
                        {{ form.hidden_tag() }}
                
                        {% for field in form %}
                        {% if field.id == 'csrf_token' %}
                        <i class="text-hide">CSRF TOKEN</i>
                        {% elif field.type == 'SubmitField' %}
                        <a class="btn btn-block btn-primary text-light text-xl py-2 border-0 rnd-xl shadow-lg disabled">
                            {{field.label}}
                        </a>
                        {% elif field.type == 'SelectField' %}
                        <div class="form-row align-items-center mb-4">
                
                            <div class="col-2">
                                <span class="text-monts text-left tet-sm my-0">
                                    {{field.label}}
                                </span>
                            </div>
                            <div class="col">
                                <div class="input-group mx-2 mb-0 ">
                                    <div class="input-group-prepend  add-anime rnd-xl">
                                        <span class="input-group-text bg-secondary text-light rnd-xl text-bold"
                                            id="inputGroupPrepend">
                                            <i class="fa{{icons(field.id)}} fa-fw ml-2 mt-0"></i>
                                        </span>
                                    </div>
                                    <input class="custom-select custom-select-sm mb-0 shadow mr-2 text-muted text-italic" type="text" name=""value="select {{field.id}}"  readonly>
                                </div>
                            </div>
                        </div>
                
                        {% else %}
                        <div class="form-row align-items-center mb-4">
                
                            <div class="col-2">
                                <span class="text-monts text-left tet-sm my-0">
                                    {{field.label}}
                                </span>
                            </div>
                            <div class="col">
                                <div class="input-group mx-2 mb-0 ">
                                    <div class="input-group-prepend  add-anime rnd-xl">
                                        <span class="input-group-text bg-secondary text-light rnd-xl text-bold"
                                            id="inputGroupPrepend">
                                            <i class="fa{{icons(field.id)}} fa-fw ml-2 mt-0"></i>
                                        </span>
                                    </div>
                                    <input class="form-control form-control-sm mb-0 shadow mr-2 text-muted text-italic" type="text" name=""value="type {{field.id}} here"  value="not authorized" readonly>
                                </div>
                            </div>
                        </div>
                
                        {% endif %}
                
                        {% endfor %}
                    </form>           
                </fieldset>
                <div class="btn-group d-flex flex-row" role="group" aria-label="Button group">
                    <a class="btn btn-secondary shadow text-lg" type="button" href="{{url_for('members.show', id=member.id )}}">
                        <i class="fas fa-times"></i>
                        Discard&Leave
                    </a>
                    <a class="btn btn-info shadow text-lg" type="button" href="{{url_for('members.edit', id=member.id )}}">
                        <i class="fas fa-undo"></i>
                        Reset&Edit
                    </a>
                    
                </div>
            </div>
        </div>
    </div>    




    
{% endif %}
    








{% endblock content %}

blueprints/templates/post.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">
  <!-- src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" -->
  <img class="rounded-circle article-img" 
    src="https://raw.githubusercontent.com/attila5287/regropoly-img/master/avatars/{{ current_user.img_url }}.png"
    >
    <div class="media-body">
      <div class="article-metadata">
        <a class="rnd-xl text-bold mr-2 px-2 py-1 disabled" href="{{ url_for('users.user_posts', id=post.author.id) }}">{{ post.author.username }}</a>
        <small class="text-italic text-light">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        <hr class="border-light my-0 mb-1 mx-5">
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}